version: '3' 

services:
  webapp: 
    build: .
    env_file: .env # 从文件中获取环境变量，可以为单独的文件路径或列表。
    # 如果通过 docker-compose -f FILE 方式来指定 Compose 模板文件，则 env_file 中变量的 路径会基于模板文件路径。
    # 如果有变量名称与 environment 指令冲突，则按照惯例，以后者为准。
    # 环境变量文件中每一行必须符合格式，支持 # 开头的注释行。
    # env_file: 
    #   - ./common.env 
    #   - ./apps/web.env 
    #   - /opt/secrets.env
    environment:  # 设置环境变量。你可以使用数组或字典两种格式。
      # 如果变量名称或者值中用到 true|false，yes|no 等表达 布尔 含义的词汇，最好放到引号 里，避免 YAML 自动解析某些内容为对应的布尔语义。这些特定词汇，包括
      # y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF
      RACK_ENV: development 
      SESSION_SECRET:
    # environment: 
    #   - RACK_ENV=development 
    #   - SESSION_SECRET