version: '3' 

services:
  webapp: 
    image: ubuntu
    logging: 
      driver: syslog # 目前支持三种日志驱动类型 driver: "json-file" driver: "syslog" driver: "none"
      options: 
        syslog-address: "tcp://192.168.0.42:123"
        max-size: "200k" 
        max-file: "10"