version: '3' 

services:
  webapp: 
    image: ubuntu
    ports:  # 使用宿主端口：容器端口 (HOST:CONTAINER) 格式，或者仅仅指定容器的端口（宿主将会随机 选择端口）都可以。
      - "3000" 
      - "8000:8000" 
      - "49100:22" 
      - "127.0.0.1:8001:8001"
      # 注意：当使用 HOST:CONTAINER 格式来映射端口时，如果你使用的容器端口小于 60 并且没放 到引号里，可能会得到错误结果，因为 YAML 会自动解析 xx:yy 这种数字格式为 60 进制。 为避免出现这种问题，建议数字串都采用引号包括起来的字符串格式。