version: '3' 

services:
  webapp: 
    image: ubuntu
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:  # 存储敏感数据，例如 mysql 服务密码。
      - db_root_password 
      - my_other_secret

secrets: 
  my_secret: 
    file: ./my_secret.txt
  my_other_secret: 
    external: true
